// Generated by CoffeeScript 1.6.1
(function() {
  var Context, Line, Point;

  Context = (function() {

    function Context(id, w, h) {
      this.canvas = document.getElementById(id);
      this.canvas.width = w;
      this.canvas.height = h;
      this.ctx = this.canvas.getContext('2d');
    }

    return Context;

  })();

  Point = (function() {

    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    Point.prototype.draw = function() {
      return this.ctx.fillRect(this.x - 2, this.y - 2, 4, 4);
    };

    return Point;

  })();

  Line = (function() {

    function Line(point1, point2) {
      this.point1 = point1;
      this.point2 = point2;
    }

    Line.prototype.draw = function() {
      this.ctx.beginPath();
      this.ctx.moveTo(this.point1.x, this.point1.y);
      this.ctx.lineTo(this.point2.x, this.point2.y);
      return this.ctx.stroke();
    };

    return Line;

  })();

  window.addEventListener('load', function() {
    var ctx, draw, prevPoint;
    ctx = new Context('canvas', 900, 600);
    Line.prototype.ctx = ctx.ctx;
    Point.prototype.ctx = ctx.ctx;
    prevPoint = null;
    draw = false;
    ctx.canvas.addEventListener('mousedown', function(ev) {
      var point;
      draw = true;
      prevPoint = point = new Point(ev.clientX, ev.clientY);
      return point.draw();
    });
    ctx.canvas.addEventListener('mouseup', function(ev) {
      var point;
      draw = false;
      prevPoint = point = new Point(ev.clientX, ev.clientY);
      return point.draw();
    });
    return ctx.canvas.addEventListener('mousemove', function(ev) {
      var line, point;
      if (!draw) {
        return;
      }
      if (Math.random() > 0.4) {
        return;
      }
      point = new Point(ev.clientX, ev.clientY);
      line = new Line(point, prevPoint);
      line.draw();
      return prevPoint = point;
    });
  });

}).call(this);
